name: exo if

on: workflow_dispatch

env:
  IFPUSH: "C'est un push!!!"
  IFREQUEST: "C'est une pull request"


jobs:
  guess_push:
    runs-on: ubuntu-latest
    steps:
      - name: "if is Push"
       # if: ${{github.event == workflow_dispatch}} trigger[list]
       # if: ${{trigger[push]}} 
        if: ${{on.push}} 
        run: echo $IFREQUEST

  # guess_pusll:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: "if is Push"
  #       if: ${{trigger[workflow_dispatch]}}
  #       run: echo $IFPUSH