name: Push or Pull

on: [push, pull_request]

env:
  PUSH: "C'est un push!!!"
  PR: "C'est une pull request"


jobs:
  push:
    if: ${{github.event_name == 'push'}} 
    runs-on: ubuntu-latest
    steps:
      - name: "Push"
        run: echo $PUSH

  pull_request:
    if: ${{github.event_name == 'pull_request'}}
    runs-on: ubuntu-latest
    steps:
      - name: "Pull request"
        run: echo $PR