name: exo if

on: [push, pull_request]

env:
  IFPUSH: "C'est un push!!!"
  IFREQUEST: "C'est une pull request"


jobs:
  guess_push:
    if: ${{github.event_name == 'push'}} 
    runs-on: ubuntu-latest
    steps:
      - name: "if is Push"
        run: echo $IFREQUEST

  guess_pusll:
    if: ${{github.event_name == 'pull_request'}}
    runs-on: ubuntu-latest
    steps:
      - name: "if is Push"
        run: echo $IFPUSH